version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: flask-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    container_name: streamlit-frontend